swagger: '2.0'
info:
  title: DICOM API
  version: 1.0.0
paths:
  /:
    get:
      description: Returns message showing app is up
      produces:
        - application/json
      responses:
        '200':
          description: Successful operation
  /upload/dicom:
    post:
      description: Upload a DICOM file
      consumes:
        - multipart/form-data
      parameters:
        - name: file
          in: formData
          description: The file to upload
          required: true
          type: file
      produces:
        - application/json
      responses:
        '201':
          description: File uploaded
        '400':
          description: Invalid file or file upload failed
  /download/png/{file_id}:
    get:
      description: Endpoint to download a file from the server
      produces:
        - application/octet-stream
      parameters:
        - name: file_id
          in: path
          required: true
          type: string
          description: ID of the file to download
      responses:
        200:
          description: File downloaded successfully
          schema:
            type: file
        404:
          description: File not found
  /header_attribute:
    get:
      description: Returns DICOM file's header attributes by ID
      parameters:
        - name: file_id
          in: query
          required: true
          type: string
          minimum: 1
          description: File ID
        - name: tag_group
          in: query
          required: true
          type: string
          minimum: 1
          description: Tag group
        - name: tag_element
          in: query
          required: true
          type: string
          minimum: 1
          description: Tag element
      produces:
        - application/json
      responses:
        '200':
          description: Header attribute objects
        '404':
          description: File ID not found 
